services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8080:8080"     # нужно, чтобы curl в раннере мог дернуть /actuator/health
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8080/actuator/health | grep -q '\"status\":\"UP\"'"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

  api-tests:
    build:
      context: .
      dockerfile: api-autotests/Dockerfile
    environment:
      BASE_URL: http://backend:8080    # имя сервиса backend внутри compose-сети
    depends_on:
      backend:
        condition: service_healthy
