spring:                           # Всё, что ниже — настройки для Spring Boot
  datasource:                     # 🔹 Раздел "источник данных" (настройка БД)
    url: jdbc:h2:mem:cardsdb      # Адрес (URL) базы данных H2
                                  # "mem" = база в памяти (удаляется после остановки приложения)
                                  # "cardsdb" = имя базы
    driver-class-name: org.h2.Driver   # Класс драйвера, который управляет подключением к H2

  thymeleaf:                      # 🔹 Раздел шаблонизатора Thymeleaf (рендерит HTML-страницы)
    cache: false                  # Отключаем кэширование шаблонов
                                  # ➜ Можно редактировать .html файлы и видеть изменения без перезапуска приложения

  h2:                             # 🔹 Раздел H2-консоли (веб-интерфейс для просмотра базы)
    console:
      enabled: true               # Включаем веб-консоль по адресу http://localhost:8080/h2-console

  jpa:                            # 🔹 Настройки JPA (Java Persistence API) — работа с БД через объекты
    hibernate:
      ddl-auto: update            # Автоматическое создание/обновление таблиц в БД по нашим @Entity классам
                                  # варианты:
                                  #   create — пересоздаёт таблицы каждый раз (данные теряются)
                                  #   update — обновляет схему, сохраняя данные
    show-sql: true                # Показывает SQL-запросы в консоли, чтобы видеть, как JPA работает под капотом
